# Generated by Django 3.1.7 on 2021-04-10 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listener',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listener',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
