# Generated by Django 3.1.7 on 2021-04-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0002_auto_20210410_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='url',
            field=models.TextField(help_text='https://example.com/api/v1/webhook'),
        ),
    ]
