# Generated by Django 3.1.7 on 2021-04-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0003_auto_20210410_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='listener',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
